url: https://needleworm.github.io/
baseurl: /dev

# Site settings
title: 비전공이지만 개발자로 먹고삽니다
email: bhban@kakao.com
description: 비전공 개발자 취업/이직 완벽 가이드

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/needleworm

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
